---
# tasks file for hnakamur.anyenv
- git: repo="{{ anyenv.git_url }}" dest="{{ anyenv.install_dir }}"

- template: src=anyenv.rc.j2 dest={{ zsh_custom_dir }}/anyenv.zsh

- shell: >
    eval "$(anyenv init -)";
    anyenv install {{ item }}
    creates={{ anyenv.install_dir }}/envs/{{ item }}
  environment:
    PATH: "{{ anyenv.install_dir }}/bin:{{ lookup('env', 'PATH') }}"
  with_items:
    - rbenv
    - ndenv
    - pyenv

- include: rbenv-version.yml
  when: rbenv.version != ""

- include: ndenv-version.yml
  when: ndenv.version != ""

- include: pyenv-version.yml
  when: pyenv.version != ""
