- homebrew: name={{ item }} state=latest
  with_items:
    - readline
    - openssl

- include: >
    env-version.yml anyenv_env_name=pyenv anyenv_env_version={{ pyenv.version }}

- pip: name={{ item }} state=present executable="{{ anyenv.install_dir }}/envs/pyenv/shims/pip"
  register: anyenv_pip_installed
  with_items: pyenv.global_packages

- shell: >
    "{{ anyenv.install_dir | replace('~', '$HOME') }}/envs/pyenv/bin/pyenv" rehash
  when: anyenv_pip_installed|changed
